apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: java-springboot-evqqgxiw
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/java-springboot-evqqgxiw:6522c1b331715dd7ac36610737c01aefc1e9df7f@sha256:44b7ffa888020a13c7466572f233e1085a2294d84e3cd3c4415413e865664a1a
        name: container-image  
